// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	entity "github.com/mariajdab/pay-gateway/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// UseCasePayment is an autogenerated mock type for the UseCasePayment type
type UseCasePayment struct {
	mock.Mock
}

// SavePaymentInfo provides a mock function with given fields: txn
func (_m *UseCasePayment) SavePaymentInfo(txn entity.Transaction) (string, error) {
	ret := _m.Called(txn)

	if len(ret) == 0 {
		panic("no return value specified for SavePaymentInfo")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(entity.Transaction) (string, error)); ok {
		return rf(txn)
	}
	if rf, ok := ret.Get(0).(func(entity.Transaction) string); ok {
		r0 = rf(txn)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(entity.Transaction) error); ok {
		r1 = rf(txn)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ValidatePaymentReq provides a mock function with given fields: paymtReq
func (_m *UseCasePayment) ValidatePaymentReq(paymtReq entity.PaymentRequest) (entity.PaymtValidateResp, error) {
	ret := _m.Called(paymtReq)

	if len(ret) == 0 {
		panic("no return value specified for ValidatePaymentReq")
	}

	var r0 entity.PaymtValidateResp
	var r1 error
	if rf, ok := ret.Get(0).(func(entity.PaymentRequest) (entity.PaymtValidateResp, error)); ok {
		return rf(paymtReq)
	}
	if rf, ok := ret.Get(0).(func(entity.PaymentRequest) entity.PaymtValidateResp); ok {
		r0 = rf(paymtReq)
	} else {
		r0 = ret.Get(0).(entity.PaymtValidateResp)
	}

	if rf, ok := ret.Get(1).(func(entity.PaymentRequest) error); ok {
		r1 = rf(paymtReq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUseCasePayment creates a new instance of UseCasePayment. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUseCasePayment(t interface {
	mock.TestingT
	Cleanup(func())
}) *UseCasePayment {
	mock := &UseCasePayment{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
