// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RepositoryCard is an autogenerated mock type for the RepositoryCard type
type RepositoryCard struct {
	mock.Mock
}

// AddCardDetail provides a mock function with given fields: cardToken, expDate, customerID
func (_m *RepositoryCard) AddCardDetail(cardToken string, expDate string, customerID int) error {
	ret := _m.Called(cardToken, expDate, customerID)

	if len(ret) == 0 {
		panic("no return value specified for AddCardDetail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, int) error); ok {
		r0 = rf(cardToken, expDate, customerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CardTokenExists provides a mock function with given fields: code
func (_m *RepositoryCard) CardTokenExists(code string) (bool, error) {
	ret := _m.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for CardTokenExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(code)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(code)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepositoryCard creates a new instance of RepositoryCard. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryCard(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryCard {
	mock := &RepositoryCard{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
