// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UseCaseCard is an autogenerated mock type for the UseCaseCard type
type UseCaseCard struct {
	mock.Mock
}

// SaveCardInfo provides a mock function with given fields: cardToken, expDate, customerID
func (_m *UseCaseCard) SaveCardInfo(cardToken string, expDate string, customerID int) error {
	ret := _m.Called(cardToken, expDate, customerID)

	if len(ret) == 0 {
		panic("no return value specified for SaveCardInfo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, int) error); ok {
		r0 = rf(cardToken, expDate, customerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUseCaseCard creates a new instance of UseCaseCard. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUseCaseCard(t interface {
	mock.TestingT
	Cleanup(func())
}) *UseCaseCard {
	mock := &UseCaseCard{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
